<ul>
<li><a href="index.html">Home</a></li>
<li><a href="#">About Us</a>
	<ul>	
		<li><a href="#">Our Team</a></li>
		<li><a href="#">Our Philosophy</a></li>
	</ul></li>
<li><a href="#">For Sellers</a></li>
<li><a href="#">For Buyers</a>
	<ul>
		<li><a href="#">Current Listings</a></li>
		<li><a href="#">Previous Listings</a></li>
	</ul></li>

<li><a href="#">Resources</a>
	<ul>
		<li><a href="#">FAQs</a></li>
		<li><a href="#">Careers</a></li>
		<li><a href="#">Policies</a></li>
	</ul></li>
<li id="contact"><a href="#">Contact Us</a></li>
</ul>